# Generated by Django 5.0 on 2024-01-04 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('YonetimWebSite', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Calisan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad', models.CharField(max_length=50)),
                ('soyad', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.DeleteModel(
            name='Kullanici',
        ),
    ]
