# Generated by Django 5.0 on 2024-01-15 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('YonetimWebSite', '0004_calisan_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='calisan',
            name='user',
        ),
    ]
