# Generated by Django 5.0 on 2024-01-15 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('YonetimWebSite', '0006_remove_calisan_email_calisan_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calisan',
            name='ad',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='calisan',
            name='soyad',
            field=models.CharField(max_length=255),
        ),
    ]
