# Generated by Django 5.0 on 2024-01-15 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('YonetimWebSite', '0007_alter_calisan_ad_alter_calisan_soyad'),
    ]

    operations = [
        migrations.AddField(
            model_name='calisan',
            name='gorevler',
            field=models.ManyToManyField(blank=True, related_name='calisanlar', to='YonetimWebSite.gorev'),
        ),
    ]
