# Generated by Django 5.0 on 2024-01-17 13:00

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('YonetimWebSite', '0009_log'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='proje',
            name='calisanlar',
            field=models.ManyToManyField(related_name='projeler', to=settings.AUTH_USER_MODEL),
        ),
    ]
